[project]
name = "na599"
version = "0.1.0"
description = "Code and data for the NA599 final project."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "freud-analysis>=3.1.0",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "scipy>=1.14.1",
]
